PROFILE_URL = 'https://stellarburgers.nomoreparties.site/account/profile'
LOGIN_URL = 'https://stellarburgers.nomoreparties.site/login'
MAIN_PAGE = 'https://stellarburgers.nomoreparties.site/'
ORDER_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
FORGOT_PASS = 'https://stellarburgers.nomoreparties.site/forgot-password'
ORDER_FEED = 'https://stellarburgers.nomoreparties.site/feed'
